### ISSUE TITLE
Создать 2 первых уровня

### ISSUE THREAD

**Issue by InnocentusLime** [nup24-gamedev-migi/src-game#10]
- [x] Уровень демонстрирующий тень
- [x] Уровень с циклом

**Comment by VenInf** [comment]
![image](https://github.com/nup24-gamedev-migi/src-game/assets/54953043/ff129024-5535-41a8-9bcc-1900fc65409c)
![image](https://github.com/nup24-gamedev-migi/src-game/assets/54953043/5de39c69-2a79-4ec4-94a3-a2b47282ef68)

**Comment by imanninen** [comment]
Если ожидалось что уровень со второй картинки использует циклы, то он их не использует. Просто обращаю на это внимание
